spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: GEjxKNCvyHfZtwiKN3pr
            client-secret: bFKlRUCGw7
            authorization-grant-type: authorization_code
            client-name: inu-malang
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            scope: profile,email

          kakao:
            client-id: d90f007e5a8a71b79ed89538c94d2dad
            client-secret: x6bROSUk9mopaBXwtveJTXYaerDH2Tmx
            authorization-grant-type: authorization_code
            client-name: client-app
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            scope: openid,profile_nickname,profile_image

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: id
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
