spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret: malangmalangmalangmalang
  access:
    expiration: 20000
    header : Authorization
  refresh:
    expiration: 30000
    header: AuthorizationRefresh

cloud:
  aws:
    s3:
      bucket: malangbucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}